(part "LTST-C170EKT"
    (packageRef "LEDC2012X120N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "122")
    (property "Manufacturer_Name" "Lite-On")
    (property "Manufacturer_Part_Number" "LTST-C170EKT")
    (property "Mouser_Part_Number" "859-LTST-C170EKT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Lite-On/LTST-C170EKT?qs=0hBTvMLoVZ04yIRvO1DUlw%3D%3D")
    (property "Arrow_Part_Number" "LTST-C170EKT")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/ltst-c170ekt/lite-on-technology")
    (property "Description" "Lite-On LTST-C170EKT, CHIPLED 0805 621 nm Red LED, 2012 (0805) SMD package")
    (property "Datasheet_Link" "https://media.digikey.com/pdf/Data%20Sheets/Lite-On%20PDFs/LTST-C170EKT.pdf")
    (property "symbolName1" "LTST-C170EKT")
)
